version: '2'
services:
  console:
    image: hpz937/magento2-console-php74
    container_name: console
    volumes:
      - magento:/srv/magento  
    ports:
      - ${SSH_PORT}:222 

  nginx:
    image: nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    # ports:
    #  - 80:80
    restart: unless-stopped
    volumes:
      - magento:/srv/magento
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/magento.conf:/etc/nginx/magento.conf:ro
  
  redis:
    image: redis:alpine
    container_name: redis-fpc
    volumes:
      - redis-fpc:/data
      - ./config/redis/page-cache/:/usr/local/etc/redis/
    command: /usr/local/etc/redis/redis.conf

  redis-session:
    image: redis:alpine
    container_name: redis-session
    volumes:
      - redis-session:/data
      - ./config/redis/session/:/usr/local/etc/redis/
    command: /usr/local/etc/redis/redis.conf

  redis-config-cache:
    image: redis:alpine
    container_name: redis-config-cache
    volumes:
      - redis-config-cache:/data
      - ./config/redis/config-cache/:/usr/local/etc/redis/
    command: /usr/local/etc/redis/redis.conf
    
  php-fpm:
    image: hpz937/magento2-php-fpm74 
    container_name: php-fpm
    volumes:
      - magento:/srv/magento

  mysql:
    image: mariadb:10.2
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      
  elastic:
    image: elasticsearch:7.12.0
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic2
      - cluster.initial_master_nodes=elastic,elastic2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic1:/usr/share/elasticsearch/data

  elastic2:
    image: elasticsearch:7.12.0
    container_name: elastic2
    environment:
      - node.name=elastic2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic
      - cluster.initial_master_nodes=elastic,elastic2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic2:/usr/share/elasticsearch/data

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=mysql

  varnish:
    container_name: varnish
    image: varnish
    restart: always
    volumes:
      - ./config/varnish/varnish.vcl:/etc/varnish/default.vcl:ro
    tmpfs:
      - /var/lib/varnish:exec

  swag:
    container_name: swag
    image: linuxserver/swag
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    cap_add:
      - NET_ADMIN
    depends_on:
      - redis
      - redis-session
      - redis-cache-config
      - mysql
      - elastic
      - elastic2
      - php-fpm
      - console
      - varnish
      - nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=${SITE_URL}
      - VALIDATION=http
      - EMAIL=${LETSENCRYPT_EMAIL}
      - MAGENTO_SERVER_DOMAIN=${SITE_URL}
    volumes:
      - swag:/config
      - ./config/swag/magento.subdomain.conf:/config/nginx/proxy-confs/magento.subdomain.conf
    restart: unless-stopped

volumes:
  elastic1:
    driver: local
  elastic2:
    driver: local
  redis-fpc:
    driver: local
  redis-session:
    driver: local
  redis-config-cache:
    driver: local
  magento:
    driver: local
  mysql:
    driver: local
  swag:
    driver: local
