version: '2'
services:
  console:
    image: hpz937/magento2-console-php73 
    container_name: console
    volumes:
      - ./data/magento:/srv/magento
    ports:
      - 222:222 

  nginx:
    image: nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    # ports:
    #  - 80:80
    restart: unless-stopped
    depends_on:
      - redis
      - mysql
      - elastic
      - php-fpm
      - console
      - varnish
      - swag
    volumes:
      - ./data/nginx:/config
      - ./data/magento:/srv/magento
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/magento.conf:/etc/nginx/magento.conf:ro
  
  redis:
    image: redis:alpine
    container_name: redis
    
  php-fpm:
    image: hpz937/magento2-php-fpm73 
    container_name: php-fpm
    volumes:
      - ./data/magento:/srv/magento

  mysql:
    image: mariadb:10.2
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      
  elastic:
    image: elasticsearch:7.12.0
    container_name: elastic
    environment:
      - discovery.type=single-node

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql

  varnish:
    container_name: varnish
    image: varnish
    restart: always
    #ports:
    #  - 80:80
    volumes:
      - ./config/varnish/varnish.vcl:/etc/varnish/default.vcl:ro
    tmpfs:
      - /var/lib/varnish:exec

  swag:
    container_name: swag
    image: linuxserver/swag
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=${SITE_URL}
      - VALIDATION=http
      - EMAIL=${LETSENCRYPT_EMAIL}
      - MAGENTO_SERVER_DOMAIN=${SITE_URL}
    volumes:
      - ./data/swag:/config
      - ./config/swag/magento.subdomain.conf:/config/nginx/proxy-confs/magento.subdomain.conf
    restart: unless-stopped
